version: "3.8"

services:
  nginx:
    build:
      context: ./
    container_name: nginx-con
    ports:
      - '80:80'
    restart: always
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge
