version: "3.8"

services:
  nginx:
    build:
      context: ./
    container_name: nginx-con
    ports:
      - '80:80'
    restart: always
    privileged: true
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    networks:
      - nginx-net

networks:
  nginx-net:
    name: nginx-net
    external: true
